### ISSUE TITLE
Can't render more than one graph per page using js helpers

### ISSUE THREAD

**Issue by ctrochalakis** [pullmonkey/open_flash_chart#1]
When one tries to render more than one graph js loading function override each other.

**Comment by ctrochalakis** [comment]
Here is a quick fix for it http://github.com/ctrochalakis/open_flash_chart/commit/658a581462b98cfa7c727c3cf369f0d300cc252a

**Comment by pullmonkey** [comment]
Thanks, finally applied your fix.
