### ISSUE TITLE
how to change background color?

### ISSUE THREAD

**Issue by ninadpachpute** [pullmonkey/open_flash_chart#11]
Hi,

Thanks a ton for this wonderful plugin.

How do we change the default background color :(
I see PHP example on ofc site but did not find any method here.

Also, I am comfirtable referring to rdocs. Why we don't have rdoc for ofc.

Ninad

**Comment by pullmonkey** [comment]
The plugin was built based on the documentation  already provided on the ofc site. So, for that reason and that every thing is funneled through method_missing,rdocs would not be as useful as you'd expect.  Use the php example, and convert it to ruby.I think the method is bg_colour.

**Comment by ninadpachpute** [comment]
Thanks a lot. That helped :)
