### ISSUE TITLE
How to set dot style?

### ISSUE THREAD

**Issue by barmstrong** [pullmonkey/open_flash_chart#2]
This should be really easy but I can't figure it out.

In the open flash chart documentation there is a function "set_default_dot_style"

I have some ruby code, but what do I pass to set_default_dot_style?

```
  line = ScatterLine.new "#000000", 3
  line.set_default_dot_style ???
  chart.add_element line
```

Thanks for creating this great plugin!

**Comment by barmstrong** [comment]
I tried a simple test trying to get something similar to the example here:
http://teethgrinder.co.uk/open-flash-chart-2/gallery/line-dash.php

Here is the JSON it generated:
    {"elements":[{"text":"my line","type":"line","dot_style":{"type":"star"},"line_style":{"style":"dash","off":8,"on":4},"font-size":12,"values":[71,74,75,70,67,69,71,71,67,62,66,65,62,66,68,72,75,76,80,82,77,80,83,45,3]}]}

But the dot style doesn't change to a star, and the line is not dashed.  Any idea what I'm doing wrong?

**Comment by pullmonkey** [comment]
Hey barmstrong, what you have looks good to me - I wonder if you just need the latest open flash chart swf file from teeth grinders site?  The ofc swf I have in the plugin likely doesn't support it.

**Comment by barmstrong** [comment]
Yep I think you're right, it has to do with the swf version.  I upgraded to the lastest version and it is definitely behaving differently.  For example, the right y axis works now.  But the lines and dots disappeared, and the dots only appear when I hover over them.  So I guess there are some small differences in the different versions.

Are there any other parts I might need to upgrade, like the swfobject.js?  I'll keep playing with it and try to generate them based off the latest ofc documentation.  Thanks again!

**Comment by barmstrong** [comment]
Oh man!  I finally figured it out.  You can see in the JSON above it has "dot_style" instead of "dot-style".  I had to add dot_style to the render list in base.rb (line 29) so that it would convert the _ to a -.

I guess if there are any other fields I can just add them there.  Glad I finally got it figured out, thanks for your help! :)

**Comment by pullmonkey** [comment]
Meant to comment before closing -- I just added dot-style to the list of attributes to convert from underscore to dash.

**Comment by barmstrong** [comment]
Thanks!
