### ISSUE TITLE
how to set label unix dates

### ISSUE THREAD

**Issue by bitcoiners** [pullmonkey/open_flash_chart#3]
Hello,
I found this http://teethgrinder.co.uk/open-flash-chart-2/x-axis-date.php
instructions for using dates for labels, but don't know how to do this with the rails plugin
x = XAxis.new
x.set_labels( ["a", "b"])
and the result  is strangely (includes labels twice)
..
"x_axis":{"labels":{"labels":["a","b"]}},
..

x.set_labels expects an array of label strings, not sure how to set the label text format to #date:l jS, M Y#

Do you have an example on a line chart with dates for x axis from unix dates? 

thank you !

**Comment by pullmonkey** [comment]
Just finished updating a bunch of the code - http://pullmonkey.com/2010/01/04/open-flash-chart-ii-for-ruby-on-rails-lug-wyrm-charmer-version/

So this seems to be working now, check out my example here - http://pullmonkey.com/2010/1/5/open-flash-chart-ii-x-axis-date-and-time/
