### ISSUE TITLE
Update readme documentation

### ISSUE THREAD

**Issue by camilonova** [pullmonkey/open_flash_chart#5]
Hi, great job.

You should add to readme that is you need to copy the contents of the 'assets' folder of the plugin to the 'public' folder of redmine, this way will be very easy to deploy your plugin.

Thanks

**Comment by pullmonkey** [comment]
Thanks.  

It was mentioned here - http://pullmonkey.com/projects/open_flash_chart2
But not in the plugin's readme.

Committed changes here - http://github.com/pullmonkey/open_flash_chart/commit/dce5523305a1de75469af37bbaa589159aea8722

Closing

**Comment by camilonova** [comment]
Thanks
