### ISSUE TITLE
Horizontal Bar Graph Tooltips

### ISSUE THREAD

**Issue by vanboom** [pullmonkey/open_flash_chart#8]
Hi - this is a fantastic plugin!  

I am having a problem with horizontal bar graphs.  If I set all starting values to zero, the mouseover tooltip gets confused and jumps around oddly.  If I stack all of the bar values so there are no overlaps, the mouseover works fine.  I think this is a bug in the SWF maybe?

thanks!

**Comment by pullmonkey** [comment]
Thanks :)

Any problems with interaction is SWF-related.
This forum will be able to help - http://forums.openflashchart.com/
